/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pemesanantiket.java
 *
 * Created on Jun 16, 2022, 2:14:00 PM
 */
package tiketbuskelompokamel;

import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class pemesanantiket extends javax.swing.JFrame {
    String t1,b1,T1,jam;

    /** Creates new form pemesanantiket 
     * 
     */
    String Cetak,kelas;
    public pemesanantiket() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
public void kelas(){
    if (rbtingkat1.isSelected()){
                  txtharga.setText("");
        if (cbnobus.getSelectedItem().equals("-")){   
         }
          if (cbnobus.getSelectedItem().equals("DJ-1")){
             txtharga.setText("100000");
         }
               if (cbnobus.getSelectedItem().equals("ALS-2")){
           
             txtharga.setText("80000");
         }
         if (cbnobus.getSelectedItem().equals("LRN-3")){
           
              txtharga.setText("70000");                   
           }
       
            
        if (cbnobus.getSelectedItem().equals("SAN-4")){
            
                   
             txtharga.setText("150000");
         }if (cbnobus.getSelectedItem().equals("AJ-5")){
            txtharga.setText("50000");
        
        }
        if (rbtingkat2.isSelected()){
            txtharga.setText("");
         if (cbnobus.getSelectedItem().equals("-")){   
         }
          if (cbnobus.getSelectedItem().equals("DJ-1")){
            
             txtharga.setText("200000");
         }
               if (cbnobus.getSelectedItem().equals("ALS-2")){
           
             txtharga.setText("100000");
         }
         if (cbnobus.getSelectedItem().equals("LRN-3")){
          
              txtharga.setText("90000");                   
           }
       
            
        if (cbnobus.getSelectedItem().equals("SAN-4")){
            
              
             txtharga.setText("200000");
         }if (cbnobus.getSelectedItem().equals("AJ-5")){
               txtharga.setText("60000");  
            }
        }
    }
}

public void jam(){
     
     if (jam1.isSelected()){
         jam = jam1.getText();
     }
     else if (jam2.isSelected()){
         jam=jam2.getText();
     }
     else if (jam3.isSelected()){
         jam =jam3.getText();
 }
     else if (jam4.isSelected()){
         jam =jam4.getText();
     }
 }

public void cetak(){
    
       int h ;
        h=JOptionPane.showConfirmDialog(null, "Cetak tiket?", "Cetak", JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE);
        if (h==JOptionPane.YES_OPTION){
            //tanggal
                    if (CbTgl.getSelectedItem().equals("Pilih")){
                        t1="";
                    }else if (CbTgl.getSelectedItem().equals("1")){
                        t1="1";
                     
                    }else if (CbTgl.getSelectedItem().equals("2")){
                        t1="2";
                    }else if (CbTgl.getSelectedItem().equals("3")){
                        t1="3";
                    }else if (CbTgl.getSelectedItem().equals("4")){
                        t1="4";
                    }else if (CbTgl.getSelectedItem().equals("5")){
                        t1="5";
                    }else if (CbTgl.getSelectedItem().equals("6")){
                        t1="6";
                    }else if (CbTgl.getSelectedItem().equals("7")){
                        t1="7";
                    }else if (CbTgl.getSelectedItem().equals("8")){
                        t1="8";
                    }else if (CbTgl.getSelectedItem().equals("9")){
                        t1="9";
                    }else if (CbTgl.getSelectedItem().equals("10")){
                        t1="10";
                    }else if (CbTgl.getSelectedItem().equals("11")){
                        t1="11";
                    }else if (CbTgl.getSelectedItem().equals("12")){
                        t1="12";
                    }else if (CbTgl.getSelectedItem().equals("13")){
                        t1="13";
                    }else if (CbTgl.getSelectedItem().equals("14")){
                        t1="14";
                    }else if (CbTgl.getSelectedItem().equals("15")){
                        t1="15";
                    }else if (CbTgl.getSelectedItem().equals("16")){
                        t1="16";
                    }else if (CbTgl.getSelectedItem().equals("17")){
                        t1="17";
                    }else if (CbTgl.getSelectedItem().equals("18")){
                        t1="18";
                    }else if (CbTgl.getSelectedItem().equals("19")){
                        t1="19";
                    }else if (CbTgl.getSelectedItem().equals("20")){
                        t1="20";
                    }else if (CbTgl.getSelectedItem().equals("21")){
                        t1="21";
                    }else if (CbTgl.getSelectedItem().equals("22")){
                        t1="22";
                    }else if (CbTgl.getSelectedItem().equals("23")){
                        t1="23";
                    }else if (CbTgl.getSelectedItem().equals("24")){
                        t1="24";
                    }else if (CbTgl.getSelectedItem().equals("25")){
                        t1="25";
                    }else if (CbTgl.getSelectedItem().equals("26")){
                        t1="26";
                    }else if (CbTgl.getSelectedItem().equals("27")){
                        t1="27";
                    }else if (CbTgl.getSelectedItem().equals("28")){
                        t1="28";
                    }else if (CbTgl.getSelectedItem().equals("29")){
                        t1="29";
                    }else if (CbTgl.getSelectedItem().equals("30")){
                        t1="30";
                    }else if (CbTgl.getSelectedItem().equals("31")){
                        CbTgl.addItem("31");
                    }
        //Bulan
                    if (CbBln.getSelectedItem().equals("Pilih")){
                        b1="";
                    }else if(CbBln.getSelectedItem().equals("Januari")){
                        b1="Januari";
                    }else if(CbBln.getSelectedItem().equals("Februari")){
                        b1="Februari";
                    }else if(CbBln.getSelectedItem().equals("Maret")){
                        b1="Maret";
                    }else if(CbBln.getSelectedItem().equals("April")){
                        b1="April";
                    }else if(CbBln.getSelectedItem().equals("Mei")){
                        b1="Mei";
                    }else if(CbBln.getSelectedItem().equals("Juni")){
                        b1="Juni";
                    }else if(CbBln.getSelectedItem().equals("Juli")){
                        b1="Juli";
                    }else if(CbBln.getSelectedItem().equals("Agustus")){
                        b1="Agustus";
                    }else if(CbBln.getSelectedItem().equals("September")){
                        b1="September";
                    }else if(CbBln.getSelectedItem().equals("Oktober")){
                        b1="Oktober";
                    }else if(CbBln.getSelectedItem().equals("November")){
                        b1="November";
                    }else if(CbBln.getSelectedItem().equals("Desember")){
                        b1="Desember";
                    }
                 //tahun
                   if (CbThn.getSelectedItem().equals("Pilih")){
                        T1="";
                    }else if (CbThn.getSelectedItem().equals("2020")){
                        T1="2020";}
 
       if (rbtingkat2.isSelected()){
           kelas=rbtingkat2.getText();
       }
       if (rbtingkat1.isSelected()){
           kelas=rbtingkat1.getText();
       }
       Cetak=" Nama                                    : "+txtnama.getText()+
           "\n Nomor Bus                               : "+cbnobus.getSelectedItem()+
           "\n Kelas                                   : "+kelas+""+
           "\n Merk Bus                                : "+txtmerkbus.getText()+
           "\n Tujuan                                  : "+txttujuan.getText()+
           "\n Tanggal Keberangkatan                   : "+t1+" "+b1+" "+T1+
           "\n Jam keberangkatan                       : "+jam+
           "\n Harga                                   : Rp. "+txtharga.getText();
       
        JOptionPane.showMessageDialog(null, Cetak ,"Data Pemesanan Tiket Pesawat" ,JOptionPane.INFORMATION_MESSAGE);
                
       
        if (h==JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null,"Silahkan periksa kembali","Cek",JOptionPane.INFORMATION_MESSAGE);
        }

 }
 }

public void clear(){
cbnobus.setSelectedItem("-");
    
txtnama.setText("");
txtharga.setText("");
txtmerkbus.setText("");
txttujuan.setText("");
buttonGroup1.clearSelection();
buttonGroup2.clearSelection();
cbnobus.setSelectedItem("-");
CbTgl.setSelectedItem("==TANNGAL==");
CbBln.setSelectedItem("==BULAN==");
CbThn.setSelectedItem("==TAHUN==");
JOptionPane.showMessageDialog(null, "Data telah di clear" ,"Clear",JOptionPane.INFORMATION_MESSAGE);


}
 

         
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        rbtingkat1 = new javax.swing.JRadioButton();
        CbThn = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jam3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jam2 = new javax.swing.JRadioButton();
        jam1 = new javax.swing.JRadioButton();
        rbtingkat2 = new javax.swing.JRadioButton();
        txtnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbnobus = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jbcetak = new javax.swing.JButton();
        jbexit = new javax.swing.JButton();
        informasi = new javax.swing.JButton();
        jam4 = new javax.swing.JRadioButton();
        CbTgl = new javax.swing.JComboBox();
        txttujuan = new javax.swing.JTextField();
        CbBln = new javax.swing.JComboBox();
        txtmerkbus = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 51));

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel8.setText("KELAS BUS");

        rbtingkat1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        rbtingkat1.setText("TINGKAT 1");
        rbtingkat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtingkat1ActionPerformed(evt);
            }
        });

        CbThn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "==TAHUN==", "2022", " " }));

        jLabel7.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel7.setText("Jam Keberangkatan");

        txtharga.setText("0");

        jLabel9.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel9.setText("Harga Rp");

        jam3.setText("16.00");
        jam3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jam3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setText("Nama");

        jam2.setText("13.00");
        jam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jam2ActionPerformed(evt);
            }
        });

        jam1.setText("09.00");
        jam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jam1ActionPerformed(evt);
            }
        });

        rbtingkat2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        rbtingkat2.setText("TINGKAT 2");
        rbtingkat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtingkat2ActionPerformed(evt);
            }
        });

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel3.setText("Nomor Bus");

        cbnobus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "DJ-1", "ALS-2", "LRN-3", "SAN-4", "AJ-5", " ", " " }));
        cbnobus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnobusActionPerformed(evt);
            }
        });

        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbcetak.setText("PRINT");
        jbcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcetakActionPerformed(evt);
            }
        });

        jbexit.setText("EXIT");
        jbexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexitActionPerformed(evt);
            }
        });

        informasi.setText("INFORMASI");
        informasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informasiActionPerformed(evt);
            }
        });

        jam4.setText("20.00");
        jam4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jam4ActionPerformed(evt);
            }
        });

        CbTgl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "==TANGGAL==", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "15", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "29", "29", "30", "31" }));

        CbBln.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "==BULAN==", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));

        jLabel4.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel4.setText("Merk BUS");

        jLabel6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel6.setText("Jadwal Keberangkatan");

        jLabel5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel5.setText("Tujuan");

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));

        jLabel1.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jLabel1.setText("PEMESANAN TIKET");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(84, 84, 84)
                        .addComponent(cbnobus, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtingkat1)
                            .addComponent(rbtingkat2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(96, 96, 96)
                        .addComponent(txtmerkbus, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(122, 122, 122)
                        .addComponent(txttujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(CbTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CbBln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CbThn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(46, 46, 46)
                        .addComponent(jam1)
                        .addGap(68, 68, 68)
                        .addComponent(jam2)
                        .addGap(54, 54, 54)
                        .addComponent(jam3)
                        .addGap(47, 47, 47)
                        .addComponent(jam4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(132, 132, 132)
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(informasi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(101, 101, 101)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(231, 231, 231)
                            .addComponent(jbcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jbexit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cbnobus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtingkat1)
                        .addGap(5, 5, 5)
                        .addComponent(rbtingkat2)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtmerkbus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txttujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6))
                    .addComponent(CbTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbBln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbThn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7))
                    .addComponent(jam1)
                    .addComponent(jam2)
                    .addComponent(jam3)
                    .addComponent(jam4))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbexit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(informasi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtnamaActionPerformed

private void jam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jam1ActionPerformed
 jam ();// TODO add your handling code here:
}//GEN-LAST:event_jam1ActionPerformed

private void informasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informasiActionPerformed
 new informasi().setVisible(true);
        this.dispose();
 
}//GEN-LAST:event_informasiActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    clear();
}//GEN-LAST:event_jButton1ActionPerformed

private void cbnobusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnobusActionPerformed
// TODO add your handling code here:
     int harga,total;
       
        if (cbnobus.getSelectedItem().equals("-")){   
         }
          if (cbnobus.getSelectedItem().equals("DJ-1")){
            txtmerkbus.setText("Dedy Jaya");
               txttujuan.setText("Pontianak-jakarta");
           
         }
               if (cbnobus.getSelectedItem().equals("ALS-2")){
            txtmerkbus.setText("Antar Lintas Sumatera (ALS)");
         txttujuan.setText("Lampung-Padang");
             
         }
         if (cbnobus.getSelectedItem().equals("LRN-3")){
            txtmerkbus.setText("Lorena");
         txttujuan.setText("Banten-Jogja");
                                
         }    
            
        if (cbnobus.getSelectedItem().equals("SAN-4")){
            
             txtmerkbus.setText("Siliwangi Antar Nusa (SAN)");      
            txttujuan.setText("Bengkulu-Riau");        
           
         }if (cbnobus.getSelectedItem().equals("AJ-5")){
            
             txtmerkbus.setText("AMEL JAYA");
         txttujuan.setText("ACEK-PAPUA");
             
 
                 
         }
        
        
        
}//GEN-LAST:event_cbnobusActionPerformed

private void jbexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexitActionPerformed
// TODO add your handling code here:
    int e;
        e=JOptionPane.showConfirmDialog(null, "Apakah anda yakin" ,"E X I T" ,JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (e==JOptionPane.YES_OPTION){
          dispose();
        }
    
}//GEN-LAST:event_jbexitActionPerformed

private void rbtingkat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtingkat1ActionPerformed
kelas();// TODO add your handling code here:
}//GEN-LAST:event_rbtingkat1ActionPerformed

private void jam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jam2ActionPerformed
 jam();// TODO add your handling code here:
}//GEN-LAST:event_jam2ActionPerformed

private void jam3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jam3ActionPerformed
jam();// TODO add your handling code here:
}//GEN-LAST:event_jam3ActionPerformed

private void jam4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jam4ActionPerformed
jam();// TODO add your handling code here:
}//GEN-LAST:event_jam4ActionPerformed

private void jbcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcetakActionPerformed
    cetak();// TODO add your handling code here:
}//GEN-LAST:event_jbcetakActionPerformed

private void rbtingkat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtingkat2ActionPerformed
kelas();// TODO add your handling code here:
}//GEN-LAST:event_rbtingkat2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemesanantiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemesanantiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemesanantiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemesanantiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new pemesanantiket().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CbBln;
    private javax.swing.JComboBox CbTgl;
    private javax.swing.JComboBox CbThn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbnobus;
    private javax.swing.JButton informasi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jam1;
    private javax.swing.JRadioButton jam2;
    private javax.swing.JRadioButton jam3;
    private javax.swing.JRadioButton jam4;
    private javax.swing.JButton jbcetak;
    private javax.swing.JButton jbexit;
    private javax.swing.JRadioButton rbtingkat1;
    private javax.swing.JRadioButton rbtingkat2;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtmerkbus;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttujuan;
    // End of variables declaration//GEN-END:variables
}
